### PR TITLE
Added the ability to play the last station directly after startup

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
Since the autostart capability (Feature Request #6) on the part of Apple is already given,
I was only missing the ability to play the last station after the program start.

Greetings Paulchen.

### CODE REVIEW

**Comment by SokoloffA** [comment]
Thank you for your help!

**Comment by Paulchen-Panther** [comment]
@SokoloffA 
Since I haven't been in the Apple world that long, I can only tell you that when you open Radiola (double-click), you get this warning.
screenshot
This is apparently because the file was not downloaded from the App Store. 
Nevertheless, I am honored to be able to help you. 😄

**Comment by SokoloffA** [comment]
At some point all browsers (chrome, firefox and safari) set the com.apple.quarantine attribute on downloaded files. 

You can either remove it, in the console: 
`xattr -d com.apple.quarantine Radiola-4.99.dmg.zip`

Or download with console wget:
`wget https://github.com/SokoloffA/radiola/files/11429245/Radiola-4.99.dmg.zip`

**Comment by Paulchen-Panther** [comment]
That is exactly the problem. Works fine and opens without warning message

**Comment by SokoloffA** [comment]
Thank you so much!
I will release a new version tomorrow

**Comment by Paulchen-Panther** [comment]
Thank you for this wonderful player 🚀

**Pull request merged**
